name: auth-service

services:
  postgres:
    image: postgres:17
    container_name: auth_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./development/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U auth_user -d auth_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    image: migrate/migrate:latest
    container_name: auth_migrations
    restart: unless-stopped
    entrypoint: [ "tail", "-f", "/dev/null" ]
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ../app/migrations:/migrations

  auth_service:
    build:
      context: ../app
      dockerfile: ../docker/Dockerfile
    container_name: auth_service
    restart: unless-stopped
    depends_on:
      - postgres
      - migrations
    env_file:
      - .env
    ports:
      - "50051:50051"

networks:
  scarymovie_net:
    external: true